/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.biovotion;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Blood pulse wave data calculated by biovotion device. */
@org.apache.avro.specific.AvroGenerated
public class BiovotionVSMBloodPulseWave extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2913301899362125263L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BiovotionVSMBloodPulseWave\",\"namespace\":\"org.radarcns.biovotion\",\"doc\":\"Blood pulse wave data calculated by biovotion device.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"bloodPulseWave\",\"type\":\"float\",\"doc\":\"Blood pulse wave value\"},{\"name\":\"bloodPulseWaveQuality\",\"type\":\"float\",\"doc\":\"Blood pulse wave quality (0-1)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** Blood pulse wave value */
  @Deprecated public float bloodPulseWave;
  /** Blood pulse wave quality (0-1) */
  @Deprecated public float bloodPulseWaveQuality;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BiovotionVSMBloodPulseWave() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param bloodPulseWave Blood pulse wave value
   * @param bloodPulseWaveQuality Blood pulse wave quality (0-1)
   */
  public BiovotionVSMBloodPulseWave(java.lang.Double time, java.lang.Double timeReceived, java.lang.Float bloodPulseWave, java.lang.Float bloodPulseWaveQuality) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.bloodPulseWave = bloodPulseWave;
    this.bloodPulseWaveQuality = bloodPulseWaveQuality;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return bloodPulseWave;
    case 3: return bloodPulseWaveQuality;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: bloodPulseWave = (java.lang.Float)value$; break;
    case 3: bloodPulseWaveQuality = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'bloodPulseWave' field.
   * @return Blood pulse wave value
   */
  public java.lang.Float getBloodPulseWave() {
    return bloodPulseWave;
  }

  /**
   * Sets the value of the 'bloodPulseWave' field.
   * Blood pulse wave value
   * @param value the value to set.
   */
  public void setBloodPulseWave(java.lang.Float value) {
    this.bloodPulseWave = value;
  }

  /**
   * Gets the value of the 'bloodPulseWaveQuality' field.
   * @return Blood pulse wave quality (0-1)
   */
  public java.lang.Float getBloodPulseWaveQuality() {
    return bloodPulseWaveQuality;
  }

  /**
   * Sets the value of the 'bloodPulseWaveQuality' field.
   * Blood pulse wave quality (0-1)
   * @param value the value to set.
   */
  public void setBloodPulseWaveQuality(java.lang.Float value) {
    this.bloodPulseWaveQuality = value;
  }

  /**
   * Creates a new BiovotionVSMBloodPulseWave RecordBuilder.
   * @return A new BiovotionVSMBloodPulseWave RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder newBuilder() {
    return new org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder();
  }

  /**
   * Creates a new BiovotionVSMBloodPulseWave RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BiovotionVSMBloodPulseWave RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder newBuilder(org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder other) {
    return new org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder(other);
  }

  /**
   * Creates a new BiovotionVSMBloodPulseWave RecordBuilder by copying an existing BiovotionVSMBloodPulseWave instance.
   * @param other The existing instance to copy.
   * @return A new BiovotionVSMBloodPulseWave RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder newBuilder(org.radarcns.biovotion.BiovotionVSMBloodPulseWave other) {
    return new org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder(other);
  }

  /**
   * RecordBuilder for BiovotionVSMBloodPulseWave instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BiovotionVSMBloodPulseWave>
    implements org.apache.avro.data.RecordBuilder<BiovotionVSMBloodPulseWave> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** Blood pulse wave value */
    private float bloodPulseWave;
    /** Blood pulse wave quality (0-1) */
    private float bloodPulseWaveQuality;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bloodPulseWave)) {
        this.bloodPulseWave = data().deepCopy(fields()[2].schema(), other.bloodPulseWave);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.bloodPulseWaveQuality)) {
        this.bloodPulseWaveQuality = data().deepCopy(fields()[3].schema(), other.bloodPulseWaveQuality);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BiovotionVSMBloodPulseWave instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.biovotion.BiovotionVSMBloodPulseWave other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bloodPulseWave)) {
        this.bloodPulseWave = data().deepCopy(fields()[2].schema(), other.bloodPulseWave);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.bloodPulseWaveQuality)) {
        this.bloodPulseWaveQuality = data().deepCopy(fields()[3].schema(), other.bloodPulseWaveQuality);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'bloodPulseWave' field.
      * Blood pulse wave value
      * @return The value.
      */
    public java.lang.Float getBloodPulseWave() {
      return bloodPulseWave;
    }

    /**
      * Sets the value of the 'bloodPulseWave' field.
      * Blood pulse wave value
      * @param value The value of 'bloodPulseWave'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder setBloodPulseWave(float value) {
      validate(fields()[2], value);
      this.bloodPulseWave = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'bloodPulseWave' field has been set.
      * Blood pulse wave value
      * @return True if the 'bloodPulseWave' field has been set, false otherwise.
      */
    public boolean hasBloodPulseWave() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'bloodPulseWave' field.
      * Blood pulse wave value
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder clearBloodPulseWave() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'bloodPulseWaveQuality' field.
      * Blood pulse wave quality (0-1)
      * @return The value.
      */
    public java.lang.Float getBloodPulseWaveQuality() {
      return bloodPulseWaveQuality;
    }

    /**
      * Sets the value of the 'bloodPulseWaveQuality' field.
      * Blood pulse wave quality (0-1)
      * @param value The value of 'bloodPulseWaveQuality'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder setBloodPulseWaveQuality(float value) {
      validate(fields()[3], value);
      this.bloodPulseWaveQuality = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'bloodPulseWaveQuality' field has been set.
      * Blood pulse wave quality (0-1)
      * @return True if the 'bloodPulseWaveQuality' field has been set, false otherwise.
      */
    public boolean hasBloodPulseWaveQuality() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'bloodPulseWaveQuality' field.
      * Blood pulse wave quality (0-1)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMBloodPulseWave.Builder clearBloodPulseWaveQuality() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public BiovotionVSMBloodPulseWave build() {
      try {
        BiovotionVSMBloodPulseWave record = new BiovotionVSMBloodPulseWave();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.bloodPulseWave = fieldSetFlags()[2] ? this.bloodPulseWave : (java.lang.Float) defaultValue(fields()[2]);
        record.bloodPulseWaveQuality = fieldSetFlags()[3] ? this.bloodPulseWaveQuality : (java.lang.Float) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
