/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.biovotion;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Respiration rate data calculated by biovotion device. */
@org.apache.avro.specific.AvroGenerated
public class BiovotionVSMRespirationRate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3452729253159402496L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BiovotionVSMRespirationRate\",\"namespace\":\"org.radarcns.biovotion\",\"doc\":\"Respiration rate data calculated by biovotion device.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"respirationRate\",\"type\":\"float\",\"doc\":\"Respiration rate value (bpm)\"},{\"name\":\"respirationRateQuality\",\"type\":\"float\",\"doc\":\"Respiration rate quality (0-1)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** Respiration rate value (bpm) */
  @Deprecated public float respirationRate;
  /** Respiration rate quality (0-1) */
  @Deprecated public float respirationRateQuality;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BiovotionVSMRespirationRate() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param respirationRate Respiration rate value (bpm)
   * @param respirationRateQuality Respiration rate quality (0-1)
   */
  public BiovotionVSMRespirationRate(java.lang.Double time, java.lang.Double timeReceived, java.lang.Float respirationRate, java.lang.Float respirationRateQuality) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.respirationRate = respirationRate;
    this.respirationRateQuality = respirationRateQuality;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return respirationRate;
    case 3: return respirationRateQuality;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: respirationRate = (java.lang.Float)value$; break;
    case 3: respirationRateQuality = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'respirationRate' field.
   * @return Respiration rate value (bpm)
   */
  public java.lang.Float getRespirationRate() {
    return respirationRate;
  }

  /**
   * Sets the value of the 'respirationRate' field.
   * Respiration rate value (bpm)
   * @param value the value to set.
   */
  public void setRespirationRate(java.lang.Float value) {
    this.respirationRate = value;
  }

  /**
   * Gets the value of the 'respirationRateQuality' field.
   * @return Respiration rate quality (0-1)
   */
  public java.lang.Float getRespirationRateQuality() {
    return respirationRateQuality;
  }

  /**
   * Sets the value of the 'respirationRateQuality' field.
   * Respiration rate quality (0-1)
   * @param value the value to set.
   */
  public void setRespirationRateQuality(java.lang.Float value) {
    this.respirationRateQuality = value;
  }

  /**
   * Creates a new BiovotionVSMRespirationRate RecordBuilder.
   * @return A new BiovotionVSMRespirationRate RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder newBuilder() {
    return new org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder();
  }

  /**
   * Creates a new BiovotionVSMRespirationRate RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BiovotionVSMRespirationRate RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder newBuilder(org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder other) {
    return new org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder(other);
  }

  /**
   * Creates a new BiovotionVSMRespirationRate RecordBuilder by copying an existing BiovotionVSMRespirationRate instance.
   * @param other The existing instance to copy.
   * @return A new BiovotionVSMRespirationRate RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder newBuilder(org.radarcns.biovotion.BiovotionVSMRespirationRate other) {
    return new org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder(other);
  }

  /**
   * RecordBuilder for BiovotionVSMRespirationRate instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BiovotionVSMRespirationRate>
    implements org.apache.avro.data.RecordBuilder<BiovotionVSMRespirationRate> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** Respiration rate value (bpm) */
    private float respirationRate;
    /** Respiration rate quality (0-1) */
    private float respirationRateQuality;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.respirationRate)) {
        this.respirationRate = data().deepCopy(fields()[2].schema(), other.respirationRate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.respirationRateQuality)) {
        this.respirationRateQuality = data().deepCopy(fields()[3].schema(), other.respirationRateQuality);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BiovotionVSMRespirationRate instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.biovotion.BiovotionVSMRespirationRate other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.respirationRate)) {
        this.respirationRate = data().deepCopy(fields()[2].schema(), other.respirationRate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.respirationRateQuality)) {
        this.respirationRateQuality = data().deepCopy(fields()[3].schema(), other.respirationRateQuality);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'respirationRate' field.
      * Respiration rate value (bpm)
      * @return The value.
      */
    public java.lang.Float getRespirationRate() {
      return respirationRate;
    }

    /**
      * Sets the value of the 'respirationRate' field.
      * Respiration rate value (bpm)
      * @param value The value of 'respirationRate'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder setRespirationRate(float value) {
      validate(fields()[2], value);
      this.respirationRate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'respirationRate' field has been set.
      * Respiration rate value (bpm)
      * @return True if the 'respirationRate' field has been set, false otherwise.
      */
    public boolean hasRespirationRate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'respirationRate' field.
      * Respiration rate value (bpm)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder clearRespirationRate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'respirationRateQuality' field.
      * Respiration rate quality (0-1)
      * @return The value.
      */
    public java.lang.Float getRespirationRateQuality() {
      return respirationRateQuality;
    }

    /**
      * Sets the value of the 'respirationRateQuality' field.
      * Respiration rate quality (0-1)
      * @param value The value of 'respirationRateQuality'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder setRespirationRateQuality(float value) {
      validate(fields()[3], value);
      this.respirationRateQuality = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'respirationRateQuality' field has been set.
      * Respiration rate quality (0-1)
      * @return True if the 'respirationRateQuality' field has been set, false otherwise.
      */
    public boolean hasRespirationRateQuality() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'respirationRateQuality' field.
      * Respiration rate quality (0-1)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMRespirationRate.Builder clearRespirationRateQuality() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public BiovotionVSMRespirationRate build() {
      try {
        BiovotionVSMRespirationRate record = new BiovotionVSMRespirationRate();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.respirationRate = fieldSetFlags()[2] ? this.respirationRate : (java.lang.Float) defaultValue(fields()[2]);
        record.respirationRateQuality = fieldSetFlags()[3] ? this.respirationRateQuality : (java.lang.Float) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
