/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.biovotion;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Data from temperature sensor expressed degrees on the Celsius (°C) scale. */
@org.apache.avro.specific.AvroGenerated
public class BiovotionVSMTemperature extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 678703689047448759L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BiovotionVSMTemperature\",\"namespace\":\"org.radarcns.biovotion\",\"doc\":\"Data from temperature sensor expressed degrees on the Celsius (°C) scale.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"temperature\",\"type\":\"float\",\"doc\":\"local temperature (°C)\"},{\"name\":\"temperatureObject\",\"type\":\"float\",\"doc\":\"object temperature (°C)\"},{\"name\":\"temperatureBarometer\",\"type\":\"float\",\"doc\":\"barometer temperature (°C)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** local temperature (°C) */
  @Deprecated public float temperature;
  /** object temperature (°C) */
  @Deprecated public float temperatureObject;
  /** barometer temperature (°C) */
  @Deprecated public float temperatureBarometer;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BiovotionVSMTemperature() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param temperature local temperature (°C)
   * @param temperatureObject object temperature (°C)
   * @param temperatureBarometer barometer temperature (°C)
   */
  public BiovotionVSMTemperature(java.lang.Double time, java.lang.Double timeReceived, java.lang.Float temperature, java.lang.Float temperatureObject, java.lang.Float temperatureBarometer) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.temperature = temperature;
    this.temperatureObject = temperatureObject;
    this.temperatureBarometer = temperatureBarometer;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return temperature;
    case 3: return temperatureObject;
    case 4: return temperatureBarometer;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: temperature = (java.lang.Float)value$; break;
    case 3: temperatureObject = (java.lang.Float)value$; break;
    case 4: temperatureBarometer = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'temperature' field.
   * @return local temperature (°C)
   */
  public java.lang.Float getTemperature() {
    return temperature;
  }

  /**
   * Sets the value of the 'temperature' field.
   * local temperature (°C)
   * @param value the value to set.
   */
  public void setTemperature(java.lang.Float value) {
    this.temperature = value;
  }

  /**
   * Gets the value of the 'temperatureObject' field.
   * @return object temperature (°C)
   */
  public java.lang.Float getTemperatureObject() {
    return temperatureObject;
  }

  /**
   * Sets the value of the 'temperatureObject' field.
   * object temperature (°C)
   * @param value the value to set.
   */
  public void setTemperatureObject(java.lang.Float value) {
    this.temperatureObject = value;
  }

  /**
   * Gets the value of the 'temperatureBarometer' field.
   * @return barometer temperature (°C)
   */
  public java.lang.Float getTemperatureBarometer() {
    return temperatureBarometer;
  }

  /**
   * Sets the value of the 'temperatureBarometer' field.
   * barometer temperature (°C)
   * @param value the value to set.
   */
  public void setTemperatureBarometer(java.lang.Float value) {
    this.temperatureBarometer = value;
  }

  /**
   * Creates a new BiovotionVSMTemperature RecordBuilder.
   * @return A new BiovotionVSMTemperature RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMTemperature.Builder newBuilder() {
    return new org.radarcns.biovotion.BiovotionVSMTemperature.Builder();
  }

  /**
   * Creates a new BiovotionVSMTemperature RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BiovotionVSMTemperature RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMTemperature.Builder newBuilder(org.radarcns.biovotion.BiovotionVSMTemperature.Builder other) {
    return new org.radarcns.biovotion.BiovotionVSMTemperature.Builder(other);
  }

  /**
   * Creates a new BiovotionVSMTemperature RecordBuilder by copying an existing BiovotionVSMTemperature instance.
   * @param other The existing instance to copy.
   * @return A new BiovotionVSMTemperature RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMTemperature.Builder newBuilder(org.radarcns.biovotion.BiovotionVSMTemperature other) {
    return new org.radarcns.biovotion.BiovotionVSMTemperature.Builder(other);
  }

  /**
   * RecordBuilder for BiovotionVSMTemperature instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BiovotionVSMTemperature>
    implements org.apache.avro.data.RecordBuilder<BiovotionVSMTemperature> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** local temperature (°C) */
    private float temperature;
    /** object temperature (°C) */
    private float temperatureObject;
    /** barometer temperature (°C) */
    private float temperatureBarometer;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.biovotion.BiovotionVSMTemperature.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.temperature)) {
        this.temperature = data().deepCopy(fields()[2].schema(), other.temperature);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.temperatureObject)) {
        this.temperatureObject = data().deepCopy(fields()[3].schema(), other.temperatureObject);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.temperatureBarometer)) {
        this.temperatureBarometer = data().deepCopy(fields()[4].schema(), other.temperatureBarometer);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BiovotionVSMTemperature instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.biovotion.BiovotionVSMTemperature other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.temperature)) {
        this.temperature = data().deepCopy(fields()[2].schema(), other.temperature);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.temperatureObject)) {
        this.temperatureObject = data().deepCopy(fields()[3].schema(), other.temperatureObject);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.temperatureBarometer)) {
        this.temperatureBarometer = data().deepCopy(fields()[4].schema(), other.temperatureBarometer);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMTemperature.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMTemperature.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMTemperature.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMTemperature.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperature' field.
      * local temperature (°C)
      * @return The value.
      */
    public java.lang.Float getTemperature() {
      return temperature;
    }

    /**
      * Sets the value of the 'temperature' field.
      * local temperature (°C)
      * @param value The value of 'temperature'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMTemperature.Builder setTemperature(float value) {
      validate(fields()[2], value);
      this.temperature = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'temperature' field has been set.
      * local temperature (°C)
      * @return True if the 'temperature' field has been set, false otherwise.
      */
    public boolean hasTemperature() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'temperature' field.
      * local temperature (°C)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMTemperature.Builder clearTemperature() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperatureObject' field.
      * object temperature (°C)
      * @return The value.
      */
    public java.lang.Float getTemperatureObject() {
      return temperatureObject;
    }

    /**
      * Sets the value of the 'temperatureObject' field.
      * object temperature (°C)
      * @param value The value of 'temperatureObject'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMTemperature.Builder setTemperatureObject(float value) {
      validate(fields()[3], value);
      this.temperatureObject = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'temperatureObject' field has been set.
      * object temperature (°C)
      * @return True if the 'temperatureObject' field has been set, false otherwise.
      */
    public boolean hasTemperatureObject() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'temperatureObject' field.
      * object temperature (°C)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMTemperature.Builder clearTemperatureObject() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperatureBarometer' field.
      * barometer temperature (°C)
      * @return The value.
      */
    public java.lang.Float getTemperatureBarometer() {
      return temperatureBarometer;
    }

    /**
      * Sets the value of the 'temperatureBarometer' field.
      * barometer temperature (°C)
      * @param value The value of 'temperatureBarometer'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMTemperature.Builder setTemperatureBarometer(float value) {
      validate(fields()[4], value);
      this.temperatureBarometer = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'temperatureBarometer' field has been set.
      * barometer temperature (°C)
      * @return True if the 'temperatureBarometer' field has been set, false otherwise.
      */
    public boolean hasTemperatureBarometer() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'temperatureBarometer' field.
      * barometer temperature (°C)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMTemperature.Builder clearTemperatureBarometer() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public BiovotionVSMTemperature build() {
      try {
        BiovotionVSMTemperature record = new BiovotionVSMTemperature();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.temperature = fieldSetFlags()[2] ? this.temperature : (java.lang.Float) defaultValue(fields()[2]);
        record.temperatureObject = fieldSetFlags()[3] ? this.temperatureObject : (java.lang.Float) defaultValue(fields()[3]);
        record.temperatureBarometer = fieldSetFlags()[4] ? this.temperatureBarometer : (java.lang.Float) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
