/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phone;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum BatteryStatus {
  UNKNOWN, CHARGING, DISCHARGING, NOT_CHARGING, FULL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BatteryStatus\",\"namespace\":\"org.radarcns.phone\",\"symbols\":[\"UNKNOWN\",\"CHARGING\",\"DISCHARGING\",\"NOT_CHARGING\",\"FULL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
