/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phone;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum LocationProvider {
  GPS, NETWORK, OTHER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LocationProvider\",\"namespace\":\"org.radarcns.phone\",\"symbols\":[\"GPS\",\"NETWORK\",\"OTHER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
