/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phone;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PhoneLockState {
  STANDBY, UNLOCKED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PhoneLockState\",\"namespace\":\"org.radarcns.phone\",\"symbols\":[\"STANDBY\",\"UNLOCKED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
