/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phone;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PhoneCallType {
  INCOMING, OUTGOING, MISSED, VOICEMAIL, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PhoneCallType\",\"namespace\":\"org.radarcns.phone\",\"symbols\":[\"INCOMING\",\"OUTGOING\",\"MISSED\",\"VOICEMAIL\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
