/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phone;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Data from the log of received and made calls. */
@org.apache.avro.specific.AvroGenerated
public class PhoneCall extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7689963218241945348L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PhoneCall\",\"namespace\":\"org.radarcns.phone\",\"doc\":\"Data from the log of received and made calls.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"duration\",\"type\":\"float\",\"doc\":\"duration of the call (s)\",\"default\":\"NaN\"},{\"name\":\"target\",\"type\":[\"null\",\"bytes\"],\"doc\":\"HMAC SHA-256 one-way source/target of the call. This hash of a given phone number will be the same unless the app is reinstalled. If the number is unknown or anonymous, this contains null.\",\"default\":null},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"PhoneCallType\",\"symbols\":[\"INCOMING\",\"OUTGOING\",\"MISSED\",\"VOICEMAIL\",\"UNKNOWN\"]},\"doc\":\"direction of phone call\",\"default\":\"UNKNOWN\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** duration of the call (s) */
  @Deprecated public float duration;
  /** HMAC SHA-256 one-way source/target of the call. This hash of a given phone number will be the same unless the app is reinstalled. If the number is unknown or anonymous, this contains null. */
  @Deprecated public java.nio.ByteBuffer target;
  /** direction of phone call */
  @Deprecated public org.radarcns.phone.PhoneCallType type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PhoneCall() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param duration duration of the call (s)
   * @param target HMAC SHA-256 one-way source/target of the call. This hash of a given phone number will be the same unless the app is reinstalled. If the number is unknown or anonymous, this contains null.
   * @param type direction of phone call
   */
  public PhoneCall(java.lang.Double time, java.lang.Double timeReceived, java.lang.Float duration, java.nio.ByteBuffer target, org.radarcns.phone.PhoneCallType type) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.duration = duration;
    this.target = target;
    this.type = type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return duration;
    case 3: return target;
    case 4: return type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: duration = (java.lang.Float)value$; break;
    case 3: target = (java.nio.ByteBuffer)value$; break;
    case 4: type = (org.radarcns.phone.PhoneCallType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'duration' field.
   * @return duration of the call (s)
   */
  public java.lang.Float getDuration() {
    return duration;
  }

  /**
   * Sets the value of the 'duration' field.
   * duration of the call (s)
   * @param value the value to set.
   */
  public void setDuration(java.lang.Float value) {
    this.duration = value;
  }

  /**
   * Gets the value of the 'target' field.
   * @return HMAC SHA-256 one-way source/target of the call. This hash of a given phone number will be the same unless the app is reinstalled. If the number is unknown or anonymous, this contains null.
   */
  public java.nio.ByteBuffer getTarget() {
    return target;
  }

  /**
   * Sets the value of the 'target' field.
   * HMAC SHA-256 one-way source/target of the call. This hash of a given phone number will be the same unless the app is reinstalled. If the number is unknown or anonymous, this contains null.
   * @param value the value to set.
   */
  public void setTarget(java.nio.ByteBuffer value) {
    this.target = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return direction of phone call
   */
  public org.radarcns.phone.PhoneCallType getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * direction of phone call
   * @param value the value to set.
   */
  public void setType(org.radarcns.phone.PhoneCallType value) {
    this.type = value;
  }

  /**
   * Creates a new PhoneCall RecordBuilder.
   * @return A new PhoneCall RecordBuilder
   */
  public static org.radarcns.phone.PhoneCall.Builder newBuilder() {
    return new org.radarcns.phone.PhoneCall.Builder();
  }

  /**
   * Creates a new PhoneCall RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PhoneCall RecordBuilder
   */
  public static org.radarcns.phone.PhoneCall.Builder newBuilder(org.radarcns.phone.PhoneCall.Builder other) {
    return new org.radarcns.phone.PhoneCall.Builder(other);
  }

  /**
   * Creates a new PhoneCall RecordBuilder by copying an existing PhoneCall instance.
   * @param other The existing instance to copy.
   * @return A new PhoneCall RecordBuilder
   */
  public static org.radarcns.phone.PhoneCall.Builder newBuilder(org.radarcns.phone.PhoneCall other) {
    return new org.radarcns.phone.PhoneCall.Builder(other);
  }

  /**
   * RecordBuilder for PhoneCall instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PhoneCall>
    implements org.apache.avro.data.RecordBuilder<PhoneCall> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** duration of the call (s) */
    private float duration;
    /** HMAC SHA-256 one-way source/target of the call. This hash of a given phone number will be the same unless the app is reinstalled. If the number is unknown or anonymous, this contains null. */
    private java.nio.ByteBuffer target;
    /** direction of phone call */
    private org.radarcns.phone.PhoneCallType type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.phone.PhoneCall.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.duration)) {
        this.duration = data().deepCopy(fields()[2].schema(), other.duration);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.target)) {
        this.target = data().deepCopy(fields()[3].schema(), other.target);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.type)) {
        this.type = data().deepCopy(fields()[4].schema(), other.type);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PhoneCall instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.phone.PhoneCall other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.duration)) {
        this.duration = data().deepCopy(fields()[2].schema(), other.duration);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.target)) {
        this.target = data().deepCopy(fields()[3].schema(), other.target);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.type)) {
        this.type = data().deepCopy(fields()[4].schema(), other.type);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneCall.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.phone.PhoneCall.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneCall.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.phone.PhoneCall.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration' field.
      * duration of the call (s)
      * @return The value.
      */
    public java.lang.Float getDuration() {
      return duration;
    }

    /**
      * Sets the value of the 'duration' field.
      * duration of the call (s)
      * @param value The value of 'duration'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneCall.Builder setDuration(float value) {
      validate(fields()[2], value);
      this.duration = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'duration' field has been set.
      * duration of the call (s)
      * @return True if the 'duration' field has been set, false otherwise.
      */
    public boolean hasDuration() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'duration' field.
      * duration of the call (s)
      * @return This builder.
      */
    public org.radarcns.phone.PhoneCall.Builder clearDuration() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'target' field.
      * HMAC SHA-256 one-way source/target of the call. This hash of a given phone number will be the same unless the app is reinstalled. If the number is unknown or anonymous, this contains null.
      * @return The value.
      */
    public java.nio.ByteBuffer getTarget() {
      return target;
    }

    /**
      * Sets the value of the 'target' field.
      * HMAC SHA-256 one-way source/target of the call. This hash of a given phone number will be the same unless the app is reinstalled. If the number is unknown or anonymous, this contains null.
      * @param value The value of 'target'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneCall.Builder setTarget(java.nio.ByteBuffer value) {
      validate(fields()[3], value);
      this.target = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'target' field has been set.
      * HMAC SHA-256 one-way source/target of the call. This hash of a given phone number will be the same unless the app is reinstalled. If the number is unknown or anonymous, this contains null.
      * @return True if the 'target' field has been set, false otherwise.
      */
    public boolean hasTarget() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'target' field.
      * HMAC SHA-256 one-way source/target of the call. This hash of a given phone number will be the same unless the app is reinstalled. If the number is unknown or anonymous, this contains null.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneCall.Builder clearTarget() {
      target = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * direction of phone call
      * @return The value.
      */
    public org.radarcns.phone.PhoneCallType getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * direction of phone call
      * @param value The value of 'type'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneCall.Builder setType(org.radarcns.phone.PhoneCallType value) {
      validate(fields()[4], value);
      this.type = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * direction of phone call
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'type' field.
      * direction of phone call
      * @return This builder.
      */
    public org.radarcns.phone.PhoneCall.Builder clearType() {
      type = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public PhoneCall build() {
      try {
        PhoneCall record = new PhoneCall();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.duration = fieldSetFlags()[2] ? this.duration : (java.lang.Float) defaultValue(fields()[2]);
        record.target = fieldSetFlags()[3] ? this.target : (java.nio.ByteBuffer) defaultValue(fields()[3]);
        record.type = fieldSetFlags()[4] ? this.type : (org.radarcns.phone.PhoneCallType) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
