/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phone;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Logs change of user interaction state: when the phone is unlocked or set to standby. */
@org.apache.avro.specific.AvroGenerated
public class PhoneUserInteraction extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2560944010872298466L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PhoneUserInteraction\",\"namespace\":\"org.radarcns.phone\",\"doc\":\"Logs change of user interaction state: when the phone is unlocked or set to standby.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"lockState\",\"type\":{\"type\":\"enum\",\"name\":\"PhoneLockState\",\"symbols\":[\"STANDBY\",\"UNLOCKED\"]},\"doc\":\"what lock state the phone has\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** what lock state the phone has */
  @Deprecated public org.radarcns.phone.PhoneLockState lockState;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PhoneUserInteraction() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param lockState what lock state the phone has
   */
  public PhoneUserInteraction(java.lang.Double time, java.lang.Double timeReceived, org.radarcns.phone.PhoneLockState lockState) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.lockState = lockState;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return lockState;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: lockState = (org.radarcns.phone.PhoneLockState)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'lockState' field.
   * @return what lock state the phone has
   */
  public org.radarcns.phone.PhoneLockState getLockState() {
    return lockState;
  }

  /**
   * Sets the value of the 'lockState' field.
   * what lock state the phone has
   * @param value the value to set.
   */
  public void setLockState(org.radarcns.phone.PhoneLockState value) {
    this.lockState = value;
  }

  /**
   * Creates a new PhoneUserInteraction RecordBuilder.
   * @return A new PhoneUserInteraction RecordBuilder
   */
  public static org.radarcns.phone.PhoneUserInteraction.Builder newBuilder() {
    return new org.radarcns.phone.PhoneUserInteraction.Builder();
  }

  /**
   * Creates a new PhoneUserInteraction RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PhoneUserInteraction RecordBuilder
   */
  public static org.radarcns.phone.PhoneUserInteraction.Builder newBuilder(org.radarcns.phone.PhoneUserInteraction.Builder other) {
    return new org.radarcns.phone.PhoneUserInteraction.Builder(other);
  }

  /**
   * Creates a new PhoneUserInteraction RecordBuilder by copying an existing PhoneUserInteraction instance.
   * @param other The existing instance to copy.
   * @return A new PhoneUserInteraction RecordBuilder
   */
  public static org.radarcns.phone.PhoneUserInteraction.Builder newBuilder(org.radarcns.phone.PhoneUserInteraction other) {
    return new org.radarcns.phone.PhoneUserInteraction.Builder(other);
  }

  /**
   * RecordBuilder for PhoneUserInteraction instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PhoneUserInteraction>
    implements org.apache.avro.data.RecordBuilder<PhoneUserInteraction> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** what lock state the phone has */
    private org.radarcns.phone.PhoneLockState lockState;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.phone.PhoneUserInteraction.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lockState)) {
        this.lockState = data().deepCopy(fields()[2].schema(), other.lockState);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PhoneUserInteraction instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.phone.PhoneUserInteraction other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lockState)) {
        this.lockState = data().deepCopy(fields()[2].schema(), other.lockState);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUserInteraction.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUserInteraction.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUserInteraction.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUserInteraction.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lockState' field.
      * what lock state the phone has
      * @return The value.
      */
    public org.radarcns.phone.PhoneLockState getLockState() {
      return lockState;
    }

    /**
      * Sets the value of the 'lockState' field.
      * what lock state the phone has
      * @param value The value of 'lockState'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUserInteraction.Builder setLockState(org.radarcns.phone.PhoneLockState value) {
      validate(fields()[2], value);
      this.lockState = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lockState' field has been set.
      * what lock state the phone has
      * @return True if the 'lockState' field has been set, false otherwise.
      */
    public boolean hasLockState() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lockState' field.
      * what lock state the phone has
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUserInteraction.Builder clearLockState() {
      lockState = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public PhoneUserInteraction build() {
      try {
        PhoneUserInteraction record = new PhoneUserInteraction();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.lockState = fieldSetFlags()[2] ? this.lockState : (org.radarcns.phone.PhoneLockState) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
