/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.avro.restapi.source;
@SuppressWarnings("all")
/** Set of device status */
@org.apache.avro.specific.AvroGenerated
public enum State {
  FINE, OK, WARNING, DISCONNECTED, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"State\",\"namespace\":\"org.radarcns.avro.restapi.source\",\"doc\":\"Set of device status\",\"symbols\":[\"FINE\",\"OK\",\"WARNING\",\"DISCONNECTED\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
