/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.avro.restapi.sensor;
@SuppressWarnings("all")
/** States if the value is provided directly by a sensor or it is computed. Any value different from RAW states who computes the value. */
@org.apache.avro.specific.AvroGenerated
public enum DataType {
  RAW, VENDOR, RADAR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DataType\",\"namespace\":\"org.radarcns.avro.restapi.sensor\",\"doc\":\"States if the value is provided directly by a sensor or it is computed. Any value different from RAW states who computes the value.\",\"symbols\":[\"RAW\",\"VENDOR\",\"RADAR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
