/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.avro.restapi.sensor;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Sensor details */
@org.apache.avro.specific.AvroGenerated
public class Sensor extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3014688017480774369L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Sensor\",\"namespace\":\"org.radarcns.avro.restapi.sensor\",\"doc\":\"Sensor details\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"enum\",\"name\":\"SensorType\",\"doc\":\"Set of sensor type\",\"symbols\":[\"ACCELEROMETER\",\"BATTERY\",\"BLOOD_VOLUME_PULSE\",\"ELECTRODERMAL_ACTIVITY\",\"INTER_BEAT_INTERVAL\",\"HEART_RATE\",\"THERMOMETER\"]},\"doc\":\"Sensor name\"},{\"name\":\"state\",\"type\":{\"type\":\"enum\",\"name\":\"State\",\"namespace\":\"org.radarcns.avro.restapi.source\",\"doc\":\"Set of device status\",\"symbols\":[\"FINE\",\"OK\",\"WARNING\",\"DISCONNECTED\",\"UNKNOWN\"]},\"doc\":\"Current sensor state computed using the received data\",\"default\":\"UNKNOWN\"},{\"name\":\"receivedMessage\",\"type\":\"int\",\"doc\":\"Amount of received messages\",\"default\":-1},{\"name\":\"messageLoss\",\"type\":\"double\",\"doc\":\"Percentage of lost messages\",\"default\":-1.0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Sensor name */
  @Deprecated public org.radarcns.avro.restapi.sensor.SensorType name;
  /** Current sensor state computed using the received data */
  @Deprecated public org.radarcns.avro.restapi.source.State state;
  /** Amount of received messages */
  @Deprecated public int receivedMessage;
  /** Percentage of lost messages */
  @Deprecated public double messageLoss;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Sensor() {}

  /**
   * All-args constructor.
   * @param name Sensor name
   * @param state Current sensor state computed using the received data
   * @param receivedMessage Amount of received messages
   * @param messageLoss Percentage of lost messages
   */
  public Sensor(org.radarcns.avro.restapi.sensor.SensorType name, org.radarcns.avro.restapi.source.State state, java.lang.Integer receivedMessage, java.lang.Double messageLoss) {
    this.name = name;
    this.state = state;
    this.receivedMessage = receivedMessage;
    this.messageLoss = messageLoss;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return state;
    case 2: return receivedMessage;
    case 3: return messageLoss;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (org.radarcns.avro.restapi.sensor.SensorType)value$; break;
    case 1: state = (org.radarcns.avro.restapi.source.State)value$; break;
    case 2: receivedMessage = (java.lang.Integer)value$; break;
    case 3: messageLoss = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return Sensor name
   */
  public org.radarcns.avro.restapi.sensor.SensorType getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * Sensor name
   * @param value the value to set.
   */
  public void setName(org.radarcns.avro.restapi.sensor.SensorType value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return Current sensor state computed using the received data
   */
  public org.radarcns.avro.restapi.source.State getState() {
    return state;
  }

  /**
   * Sets the value of the 'state' field.
   * Current sensor state computed using the received data
   * @param value the value to set.
   */
  public void setState(org.radarcns.avro.restapi.source.State value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'receivedMessage' field.
   * @return Amount of received messages
   */
  public java.lang.Integer getReceivedMessage() {
    return receivedMessage;
  }

  /**
   * Sets the value of the 'receivedMessage' field.
   * Amount of received messages
   * @param value the value to set.
   */
  public void setReceivedMessage(java.lang.Integer value) {
    this.receivedMessage = value;
  }

  /**
   * Gets the value of the 'messageLoss' field.
   * @return Percentage of lost messages
   */
  public java.lang.Double getMessageLoss() {
    return messageLoss;
  }

  /**
   * Sets the value of the 'messageLoss' field.
   * Percentage of lost messages
   * @param value the value to set.
   */
  public void setMessageLoss(java.lang.Double value) {
    this.messageLoss = value;
  }

  /**
   * Creates a new Sensor RecordBuilder.
   * @return A new Sensor RecordBuilder
   */
  public static org.radarcns.avro.restapi.sensor.Sensor.Builder newBuilder() {
    return new org.radarcns.avro.restapi.sensor.Sensor.Builder();
  }

  /**
   * Creates a new Sensor RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Sensor RecordBuilder
   */
  public static org.radarcns.avro.restapi.sensor.Sensor.Builder newBuilder(org.radarcns.avro.restapi.sensor.Sensor.Builder other) {
    return new org.radarcns.avro.restapi.sensor.Sensor.Builder(other);
  }

  /**
   * Creates a new Sensor RecordBuilder by copying an existing Sensor instance.
   * @param other The existing instance to copy.
   * @return A new Sensor RecordBuilder
   */
  public static org.radarcns.avro.restapi.sensor.Sensor.Builder newBuilder(org.radarcns.avro.restapi.sensor.Sensor other) {
    return new org.radarcns.avro.restapi.sensor.Sensor.Builder(other);
  }

  /**
   * RecordBuilder for Sensor instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Sensor>
    implements org.apache.avro.data.RecordBuilder<Sensor> {

    /** Sensor name */
    private org.radarcns.avro.restapi.sensor.SensorType name;
    /** Current sensor state computed using the received data */
    private org.radarcns.avro.restapi.source.State state;
    /** Amount of received messages */
    private int receivedMessage;
    /** Percentage of lost messages */
    private double messageLoss;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.avro.restapi.sensor.Sensor.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.state)) {
        this.state = data().deepCopy(fields()[1].schema(), other.state);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.receivedMessage)) {
        this.receivedMessage = data().deepCopy(fields()[2].schema(), other.receivedMessage);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.messageLoss)) {
        this.messageLoss = data().deepCopy(fields()[3].schema(), other.messageLoss);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Sensor instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.avro.restapi.sensor.Sensor other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.state)) {
        this.state = data().deepCopy(fields()[1].schema(), other.state);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.receivedMessage)) {
        this.receivedMessage = data().deepCopy(fields()[2].schema(), other.receivedMessage);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.messageLoss)) {
        this.messageLoss = data().deepCopy(fields()[3].schema(), other.messageLoss);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * Sensor name
      * @return The value.
      */
    public org.radarcns.avro.restapi.sensor.SensorType getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * Sensor name
      * @param value The value of 'name'.
      * @return This builder.
      */
    public org.radarcns.avro.restapi.sensor.Sensor.Builder setName(org.radarcns.avro.restapi.sensor.SensorType value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Sensor name
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * Sensor name
      * @return This builder.
      */
    public org.radarcns.avro.restapi.sensor.Sensor.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * Current sensor state computed using the received data
      * @return The value.
      */
    public org.radarcns.avro.restapi.source.State getState() {
      return state;
    }

    /**
      * Sets the value of the 'state' field.
      * Current sensor state computed using the received data
      * @param value The value of 'state'.
      * @return This builder.
      */
    public org.radarcns.avro.restapi.sensor.Sensor.Builder setState(org.radarcns.avro.restapi.source.State value) {
      validate(fields()[1], value);
      this.state = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * Current sensor state computed using the received data
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'state' field.
      * Current sensor state computed using the received data
      * @return This builder.
      */
    public org.radarcns.avro.restapi.sensor.Sensor.Builder clearState() {
      state = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'receivedMessage' field.
      * Amount of received messages
      * @return The value.
      */
    public java.lang.Integer getReceivedMessage() {
      return receivedMessage;
    }

    /**
      * Sets the value of the 'receivedMessage' field.
      * Amount of received messages
      * @param value The value of 'receivedMessage'.
      * @return This builder.
      */
    public org.radarcns.avro.restapi.sensor.Sensor.Builder setReceivedMessage(int value) {
      validate(fields()[2], value);
      this.receivedMessage = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'receivedMessage' field has been set.
      * Amount of received messages
      * @return True if the 'receivedMessage' field has been set, false otherwise.
      */
    public boolean hasReceivedMessage() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'receivedMessage' field.
      * Amount of received messages
      * @return This builder.
      */
    public org.radarcns.avro.restapi.sensor.Sensor.Builder clearReceivedMessage() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'messageLoss' field.
      * Percentage of lost messages
      * @return The value.
      */
    public java.lang.Double getMessageLoss() {
      return messageLoss;
    }

    /**
      * Sets the value of the 'messageLoss' field.
      * Percentage of lost messages
      * @param value The value of 'messageLoss'.
      * @return This builder.
      */
    public org.radarcns.avro.restapi.sensor.Sensor.Builder setMessageLoss(double value) {
      validate(fields()[3], value);
      this.messageLoss = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'messageLoss' field has been set.
      * Percentage of lost messages
      * @return True if the 'messageLoss' field has been set, false otherwise.
      */
    public boolean hasMessageLoss() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'messageLoss' field.
      * Percentage of lost messages
      * @return This builder.
      */
    public org.radarcns.avro.restapi.sensor.Sensor.Builder clearMessageLoss() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public Sensor build() {
      try {
        Sensor record = new Sensor();
        record.name = fieldSetFlags()[0] ? this.name : (org.radarcns.avro.restapi.sensor.SensorType) defaultValue(fields()[0]);
        record.state = fieldSetFlags()[1] ? this.state : (org.radarcns.avro.restapi.source.State) defaultValue(fields()[1]);
        record.receivedMessage = fieldSetFlags()[2] ? this.receivedMessage : (java.lang.Integer) defaultValue(fields()[2]);
        record.messageLoss = fieldSetFlags()[3] ? this.messageLoss : (java.lang.Double) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
