/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.avro.restapi.sensor;
@SuppressWarnings("all")
/** Set of sensor type */
@org.apache.avro.specific.AvroGenerated
public enum SensorType {
  ACCELEROMETER, BATTERY, BLOOD_VOLUME_PULSE, ELECTRODERMAL_ACTIVITY, INTER_BEAT_INTERVAL, HEART_RATE, THERMOMETER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SensorType\",\"namespace\":\"org.radarcns.avro.restapi.sensor\",\"doc\":\"Set of sensor type\",\"symbols\":[\"ACCELEROMETER\",\"BATTERY\",\"BLOOD_VOLUME_PULSE\",\"ELECTRODERMAL_ACTIVITY\",\"INTER_BEAT_INTERVAL\",\"HEART_RATE\",\"THERMOMETER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
