/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.avro.restapi.sensor;
@SuppressWarnings("all")
/** Set of measurement units */
@org.apache.avro.specific.AvroGenerated
public enum Unit {
  BEATS_PER_MIN, CELSIUS, DIMENSIONLESS, G, MICROSIEMENS, SECOND, NANOWATT, PERCENTAGE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Unit\",\"namespace\":\"org.radarcns.avro.restapi.sensor\",\"doc\":\"Set of measurement units\",\"symbols\":[\"BEATS_PER_MIN\",\"CELSIUS\",\"DIMENSIONLESS\",\"G\",\"MICROSIEMENS\",\"SECOND\",\"NANOWATT\",\"PERCENTAGE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
