{
  "namespace": "org.radarcns.push.googlehealth",
  "type": "record",
  "name": "GoogleHealthExerciseHeartRate",
  "doc": "Aggregate heart rate measured over an exercise session, including time spent in each heart rate zone.",
  "fields": [
    { "name": "mean", "type": ["null", "int"], "doc": "Mean heart rate over the duration of the exercise (bpm). Null if unknown.", "default": null },
    { "name": "durationLight", "type": ["null", "int"], "doc": "Time spent in the light heart rate zone during the exercise (s). Null if unknown.", "default": null },
    { "name": "durationModerate", "type": ["null", "int"], "doc": "Time spent in the moderate heart rate zone during the exercise (s). Null if unknown.", "default": null },
    { "name": "durationVigorous", "type": ["null", "int"], "doc": "Time spent in the vigorous heart rate zone during the exercise (s). Null if unknown.", "default": null },
    { "name": "durationPeak", "type": ["null", "int"], "doc": "Time spent in the peak heart rate zone during the exercise (s). Null if unknown.", "default": null }
  ]
}
