{
  "namespace": "org.radarcns.push.googlehealth",
  "type": "record",
  "name": "GoogleHealthRespiratoryRateSleepSummary",
  "doc": "Google Health respiratory rate details during sleep. Can have multiple per day if the user sleeps multiple times.",
  "fields": [
    { "name": "time", "type": "double", "doc": "Device timestamp in UTC (s)." },
    { "name": "timeReceived", "type": "double", "doc": "Time this record was collected by the connector, seconds since the Unix Epoch." },
    { "name": "lightSleep", "type": "float", "doc": "Average number of breaths taken per minute when the user was in light sleep." },
    { "name": "deepSleep", "type": "float", "doc": "Average number of breaths taken per minute when the user was in deep sleep." },
    { "name": "remSleep", "type": "float", "doc": "Average number of breaths taken per minute when the user was in rem sleep." },
    { "name": "fullSleep", "type": "float", "doc": "Average number of breaths taken per minute throughout the entire period of sleep which you can compare to the sleep stage-specific measurements." }
  ]
}
