{
  "namespace": "org.radarcns.connector.huawei",
  "type": "record",
  "name": "HuaweiHealthRecordMenstrualCycle",
  "doc": "Huawei Health Kit REST data for com.huawei.health.record.menstrual_cycle. See Huawei HMS Core Health Kit RESTful data type documentation.",
  "fields": [
    {
      "name": "time",
      "type": "double",
      "doc": "Start time of the sample or record in UTC (s)."
    },
    {
      "name": "timeReceived",
      "type": "double",
      "doc": "Time the connector received this record from the Huawei Health API (s)."
    },
    {
      "name": "endTime",
      "type": [
        "null",
        "double"
      ],
      "doc": "End time of the sample or record in UTC (s), when provided by Huawei.",
      "default": null
    },
    {
      "name": "recordday",
      "type": [
        "null",
        "int"
      ],
      "doc": "Value of Huawei field 'recordDay' for data type com.huawei.health.record.menstrual_cycle.",
      "default": null
    },
    {
      "name": "status",
      "type": [
        "null",
        "int"
      ],
      "doc": "Value of Huawei field 'status' for data type com.huawei.health.record.menstrual_cycle.",
      "default": null
    },
    {
      "name": "substatus",
      "type": [
        "null",
        "int"
      ],
      "doc": "Value of Huawei field 'subStatus' for data type com.huawei.health.record.menstrual_cycle.",
      "default": null
    },
    {
      "name": "remarks",
      "type": [
        "null",
        "string"
      ],
      "doc": "Value of Huawei field 'remarks' for data type com.huawei.health.record.menstrual_cycle.",
      "default": null
    },
    {
      "name": "timezone",
      "type": [
        "null",
        "string"
      ],
      "doc": "Value of Huawei field 'timeZone' for data type com.huawei.health.record.menstrual_cycle.",
      "default": null
    }
  ]
}
