{
  "namespace": "org.radarcns.connector.huawei",
  "type": "record",
  "name": "HuaweiInstantaneousActivitySamples",
  "doc": "Huawei Health Kit REST data for com.huawei.instantaneous.activity.samples. See Huawei HMS Core Health Kit RESTful data type documentation.",
  "fields": [
    {
      "name": "time",
      "type": "double",
      "doc": "Start time of the sample or record in UTC (s)."
    },
    {
      "name": "timeReceived",
      "type": "double",
      "doc": "Time the connector received this record from the Huawei Health API (s)."
    },
    {
      "name": "endTime",
      "type": [
        "null",
        "double"
      ],
      "doc": "End time of the sample or record in UTC (s), when provided by Huawei.",
      "default": null
    },
    {
      "name": "possibilityOfActivity",
      "type": [
        "null",
        "double"
      ],
      "doc": "Confidence that the detected activity type is correct, ranging from 0.0 to 100.0.",
      "default": null
    }
  ]
}
