{
  "namespace": "org.radarcns.connector.huawei",
  "type": "record",
  "name": "HuaweiHealthRecordTachycardia",
  "doc": "Huawei Health Kit REST data for com.huawei.health.record.tachycardia. See Huawei HMS Core Health Kit RESTful data type documentation.",
  "fields": [
    {
      "name": "time",
      "type": "double",
      "doc": "Start time of the sample or record in UTC (s)."
    },
    {
      "name": "timeReceived",
      "type": "double",
      "doc": "Time the connector received this record from the Huawei Health API (s)."
    },
    {
      "name": "endTime",
      "type": [
        "null",
        "double"
      ],
      "doc": "End time of the sample or record in UTC (s), when provided by Huawei.",
      "default": null
    },
    {
      "name": "threshold",
      "type": [
        "null",
        "double"
      ],
      "doc": "Value of Huawei field 'threshold' for data type com.huawei.health.record.tachycardia.",
      "default": null
    },
    {
      "name": "avgHeartRate",
      "type": [
        "null",
        "double"
      ],
      "doc": "Value of Huawei field 'avg_heart_rate' for data type com.huawei.health.record.tachycardia.",
      "default": null
    },
    {
      "name": "maxHeartRate",
      "type": [
        "null",
        "double"
      ],
      "doc": "Value of Huawei field 'max_heart_rate' for data type com.huawei.health.record.tachycardia.",
      "default": null
    },
    {
      "name": "minHeartRate",
      "type": [
        "null",
        "double"
      ],
      "doc": "Value of Huawei field 'min_heart_rate' for data type com.huawei.health.record.tachycardia.",
      "default": null
    }
  ]
}
