{
  "namespace": "org.radarcns.connector.huawei",
  "type": "record",
  "name": "HuaweiInstantaneousNutritionFacts",
  "doc": "Huawei Health Kit REST data for com.huawei.instantaneous.nutrition_facts. See Huawei HMS Core Health Kit RESTful data type documentation.",
  "fields": [
    {
      "name": "time",
      "type": "double",
      "doc": "Start time of the sample or record in UTC (s)."
    },
    {
      "name": "timeReceived",
      "type": "double",
      "doc": "Time the connector received this record from the Huawei Health API (s)."
    },
    {
      "name": "endTime",
      "type": [
        "null",
        "double"
      ],
      "doc": "End time of the sample or record in UTC (s), when provided by Huawei.",
      "default": null
    },
    {
      "name": "nutrientsFacts",
      "type": [
        "null",
        "string"
      ],
      "doc": "Value of Huawei field 'nutrients_facts' for data type com.huawei.instantaneous.nutrition_facts. Stored as a JSON string when the source value is a map.",
      "default": null
    },
    {
      "name": "meal",
      "type": [
        "null",
        "int"
      ],
      "doc": "Value of Huawei field 'meal' for data type com.huawei.instantaneous.nutrition_facts.",
      "default": null
    },
    {
      "name": "food",
      "type": [
        "null",
        "string"
      ],
      "doc": "Value of Huawei field 'food' for data type com.huawei.instantaneous.nutrition_facts.",
      "default": null
    }
  ]
}
