{
  "namespace": "org.radarcns.connector.huawei",
  "type": "record",
  "name": "HuaweiInstantaneousUrineRoutineUrobilinogen",
  "doc": "A single urine urobilinogen level result from a urine routine test strip, as collected by the Huawei Health Kit instantaneous.urine_routine.urobilinogen data type.",
  "fields": [
    {
      "name": "time",
      "type": "double",
      "doc": "Start time of the sample or record in UTC (s)."
    },
    {
      "name": "timeReceived",
      "type": "double",
      "doc": "Time the connector received this record from the Huawei Health API (s)."
    },
    {
      "name": "urobilinogen",
      "type": [
        "null",
        "int"
      ],
      "doc": "Urobilinogen level in the urine routine test result.",
      "default": null
    }
  ]
}
