{
  "namespace": "org.radarcns.connector.huawei",
  "type": "record",
  "name": "HuaweiRestingCaloriesStatistics",
  "doc": "Huawei Health Kit REST data for com.huawei.resting_calories.statistics. See Huawei HMS Core Health Kit RESTful data type documentation.",
  "fields": [
    {
      "name": "time",
      "type": "double",
      "doc": "Start time of the sample or record in UTC (s)."
    },
    {
      "name": "timeReceived",
      "type": "double",
      "doc": "Time the connector received this record from the Huawei Health API (s)."
    },
    {
      "name": "endTime",
      "type": [
        "null",
        "double"
      ],
      "doc": "End time of the sample or record in UTC (s), when provided by Huawei.",
      "default": null
    },
    {
      "name": "predictedCalories",
      "type": [
        "null",
        "float"
      ],
      "doc": "Predicted calorie expenditure (kcal).",
      "default": null
    },
    {
      "name": "totalCalories",
      "type": [
        "null",
        "float"
      ],
      "doc": "Total energy expenditure including resting metabolism (kcal).",
      "default": null
    }
  ]
}
