{
  "namespace": "org.radarcns.connector.huawei",
  "type": "record",
  "name": "HuaweiInstantaneousRestingHeartRate",
  "doc": "A single resting heart rate measurement recorded when the user is at rest, as collected by the Huawei Health Kit instantaneous.resting_heart_rate data type.",
  "fields": [
    {
      "name": "time",
      "type": "double",
      "doc": "Start time of the sample or record in UTC (s)."
    },
    {
      "name": "timeReceived",
      "type": "double",
      "doc": "Time the connector received this record from the Huawei Health API (s)."
    },
    {
      "name": "bpm",
      "type": [
        "null",
        "double"
      ],
      "doc": "Heart rate (bpm).",
      "default": null
    }
  ]
}
