{
  "namespace": "org.radarcns.connector.huawei",
  "type": "record",
  "name": "HuaweiSleepOnOffBedRecord",
  "doc": "Huawei Health Kit REST data for com.huawei.sleep.on_off_bed_record. See Huawei HMS Core Health Kit RESTful data type documentation.",
  "fields": [
    {
      "name": "time",
      "type": "double",
      "doc": "Start time of the sample or record in UTC (s)."
    },
    {
      "name": "timeReceived",
      "type": "double",
      "doc": "Time the connector received this record from the Huawei Health API (s)."
    },
    {
      "name": "endTime",
      "type": [
        "null",
        "double"
      ],
      "doc": "End time of the sample or record in UTC (s), when provided by Huawei.",
      "default": null
    },
    {
      "name": "onOffBedState",
      "type": [
        "null",
        "int"
      ],
      "doc": "Bed occupancy state: indicates whether the user is in or out of bed.",
      "default": null
    }
  ]
}
