{
  "namespace": "org.radarcns.connector.huawei",
  "type": "record",
  "name": "HuaweiHealthRecordHyperthermia",
  "doc": "Huawei Health Kit REST data for com.huawei.health.record.hyperthermia. See Huawei HMS Core Health Kit RESTful data type documentation.",
  "fields": [
    {
      "name": "time",
      "type": "double",
      "doc": "Start time of the sample or record in UTC (s)."
    },
    {
      "name": "timeReceived",
      "type": "double",
      "doc": "Time the connector received this record from the Huawei Health API (s)."
    },
    {
      "name": "endTime",
      "type": [
        "null",
        "double"
      ],
      "doc": "End time of the sample or record in UTC (s), when provided by Huawei.",
      "default": null
    },
    {
      "name": "highBodyTemperatureAlarm",
      "type": [
        "null",
        "float"
      ],
      "doc": "Flag indicating a high body temperature alarm was triggered.",
      "default": null
    }
  ]
}
