/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.avro.restapi.app;
@SuppressWarnings("all")
/** Set of device status */
@org.apache.avro.specific.AvroGenerated
public enum ServerStatus {
  CONNECTED, DISCONNECTED, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ServerStatus\",\"namespace\":\"org.radarcns.avro.restapi.app\",\"doc\":\"Set of device status\",\"symbols\":[\"CONNECTED\",\"DISCONNECTED\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
