# Continuous integration, including test and integration test
name: Publish snapshots

# Run in master and dev branches and in all pull requests to those branches
on:
  push:
    branches: [ dev ]

jobs:
  # Build and test the code
  java:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: java-sdk

    steps:
      - uses: actions/checkout@v4

      - name: Has SNAPSHOT version
        id: is-snapshot
        run: grep 'const val project = ".*-SNAPSHOT"' buildSrc/src/main/kotlin/Versions.kt

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Compile code
        run: ./gradlew assemble

      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER_TOKEN_ID }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_USER_TOKEN_SECRET }}
        run: ./gradlew -Psigning.gnupg.keyName=${{ secrets.OSSRH_GPG_SECRET_KEY_NAME }} -Psigning.gnupg.executable=gpg -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} publish
